"""add_otp_expiry

Revision ID: 232214ef9617
Revises: dd966e675178
Create Date: 2026-05-27 13:02:59.557304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232214ef9617'
down_revision: Union[str, Sequence[str], None] = 'dd966e675178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_verification_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_verification_expires_at')
    # ### end Alembic commands ###
