"""Add messages table

Revision ID: 245999370393
Revises: 7b07b77be7cb
Create Date: 2026-05-14 17:07:53.895586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245999370393'
down_revision: Union[str, Sequence[str], None] = '7b07b77be7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('ai_suggestion_confidence', sa.Float(), nullable=True),
    sa.Column('ai_suggestion_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
