"""Add whatsapp_connected

Revision ID: 76bb19fb071c
Revises: 245999370393
Create Date: 2026-05-14 19:09:38.749324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bb19fb071c'
down_revision: Union[str, Sequence[str], None] = '245999370393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp_connected')
    # ### end Alembic commands ###
