"""Add terms_accepted to users

Revision ID: 7b1ec5ff1260
Revises: 76bb19fb071c
Create Date: 2026-05-16 14:05:28.688263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1ec5ff1260'
down_revision: Union[str, Sequence[str], None] = '76bb19fb071c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_accepted')
    # ### end Alembic commands ###
