"""Add twilio sandbox credentials

Revision ID: 9f8e7d6c5b4a
Revises: c8d57e886faf
Create Date: 2026-05-23 18:08:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8e7d6c5b4a'
down_revision: Union[str, None] = 'c8d57e886faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twilio_account_sid', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twilio_auth_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twilio_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twilio_phone_number')
    op.drop_column('users', 'twilio_auth_token')
    op.drop_column('users', 'twilio_account_sid')
    # ### end Alembic commands ###
