"""Add WA credentials to users and conversation fields to messages

Revision ID: c8d57e886faf
Revises: 7b1ec5ff1260
Create Date: 2026-05-16 17:19:55.924860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d57e886faf'
down_revision: Union[str, Sequence[str], None] = '7b1ec5ff1260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_phone', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('direction', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('wa_message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_sender_phone'), 'messages', ['sender_phone'], unique=False)
    op.create_unique_constraint(None, 'messages', ['wa_message_id'])
    op.add_column('users', sa.Column('wa_phone_number_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wa_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wa_business_account_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wa_webhook_verify_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wa_webhook_verify_token')
    op.drop_column('users', 'wa_business_account_id')
    op.drop_column('users', 'wa_access_token')
    op.drop_column('users', 'wa_phone_number_id')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_index(op.f('ix_messages_sender_phone'), table_name='messages')
    op.drop_column('messages', 'wa_message_id')
    op.drop_column('messages', 'direction')
    op.drop_column('messages', 'sender_phone')
    # ### end Alembic commands ###
