"""add_user_id_to_messages

Revision ID: dd966e675178
Revises: bd90e95baf29
Create Date: 2026-05-27 12:13:16.067761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd966e675178'
down_revision: Union[str, Sequence[str], None] = 'bd90e95baf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
