"""add_user_id_to_various_tables

Revision ID: e1a2b3c4d5e6
Revises: d45e83c7d6e5
Create Date: 2026-05-30 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a2b3c4d5e6'
down_revision: Union[str, Sequence[str], None] = 'd45e83c7d6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])
    
    op.add_column('deals', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_deals_user_id'), 'deals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'deals', 'users', ['user_id'], ['id'])
    
    op.add_column('escalations', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_escalations_user_id'), 'escalations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'escalations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.drop_index(op.f('ix_escalations_user_id'), table_name='escalations')
    op.drop_column('escalations', 'user_id')
    
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_index(op.f('ix_deals_user_id'), table_name='deals')
    op.drop_column('deals', 'user_id')
    
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
